version: "3.3"
volumes:
  pgdata:
services:
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=${KAFKA_HOST}
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  queue:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
  memory:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
